apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "trial-service"
    spec:
      selector:
        app: "trial-service"
      type: LoadBalancer
      ports:
        - name: http
          port: 8080
          targetPort: 8080
          nodePort: 32000
          protocol: TCP
  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      labels:
        app: "trial-service"
      name: "trial-service"
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: "trial-service"
      template:
        metadata:
          labels:
            app: "trial-service"
        spec:
          containers:
            - image: "trial:latest"
              imagePullPolicy: "Never"
              name: "trial-service"
              resources:
                limits:
                  cpu: 500m
                requests:
                  cpu: 200m
              ports:
                - protocol: TCP
                  containerPort: 8080
